// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh3GQB74DwdovPlwDm8S0An1_a7tUnnGs',
    appId: '1:791170873077:web:7f5d00bec763ca5eacb7bc',
    messagingSenderId: '791170873077',
    projectId: 'incrementapps',
    authDomain: 'incrementapps.firebaseapp.com',
    storageBucket: 'incrementapps.appspot.com',
    measurementId: 'G-CX8C9BMKB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyhBM-jfHUn1Fm1v1tUWUV2mZZIlZ_eT0',
    appId: '1:791170873077:android:c306b6d6761a3edfacb7bc',
    messagingSenderId: '791170873077',
    projectId: 'incrementapps',
    storageBucket: 'incrementapps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYPXMaeYDMPUjPq7txb4KfwnwrcD80r7U',
    appId: '1:791170873077:ios:561a87b7b6949e24acb7bc',
    messagingSenderId: '791170873077',
    projectId: 'incrementapps',
    storageBucket: 'incrementapps.appspot.com',
    iosBundleId: 'com.example.userIncrement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYPXMaeYDMPUjPq7txb4KfwnwrcD80r7U',
    appId: '1:791170873077:ios:561a87b7b6949e24acb7bc',
    messagingSenderId: '791170873077',
    projectId: 'incrementapps',
    storageBucket: 'incrementapps.appspot.com',
    iosBundleId: 'com.example.userIncrement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh3GQB74DwdovPlwDm8S0An1_a7tUnnGs',
    appId: '1:791170873077:web:53e5cae920f5e462acb7bc',
    messagingSenderId: '791170873077',
    projectId: 'incrementapps',
    authDomain: 'incrementapps.firebaseapp.com',
    storageBucket: 'incrementapps.appspot.com',
    measurementId: 'G-N9EFQ4Q5PG',
  );
}
